version: '3.8'
services:
  # web:
  # build: .
  # volumes:
  #   - .:/usr/app
  #   - /usr/app/node_modules
  # ports:
  #   - 3000:3000
  # environment:
  #   - HOST=postgres
  # depends_on:
  #   - postgres

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: stocks
    ports:
      - 10000:5432
    volumes:
      - './pgdata/:/var/lib/postgresql/data'
  redis-client:
    image: redis:alpine
    ports:
      - 6379:6379
